### PR TITLE
Mix target layout

### PR DESCRIPTION
**Pull request by felicialim**
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/iac/pull/117.html" title="Last updated on Oct 24, 2022, 11:12 PM UTC (5fb9eb2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/iac/117/a6308e1...5fb9eb2.html" title="Last updated on Oct 24, 2022, 11:12 PM UTC (5fb9eb2)">Diff</a>

### CODE REVIEW

**Review by sunghee-hwang — COMMENTED** [review]
The updates on render_config() will be conflicted with #112. Please check it.

**Comment by tdaede** [comment]
This adds a huge amount of flexibility. How are regular e.g. 5.1 streams supported in this scheme?

**Comment by felicialim** [comment]
> This adds a huge amount of flexibility. How are regular e.g. 5.1 streams supported in this scheme?

Right, we would have to ensure that renderer can support these layouts.

5.1 would specify `sound_system = B`.

**Comment by felicialim** [comment]
> The updates on render_config() will be conflicted with #112. Please check it.

Done.

**Comment by tdaede** [comment]
Can you rebase this one more time?

**Comment by tdaede** [comment]
I can rebase it too if you'd rather I do.

**Review by tdaede — APPROVED** [review]

**Review by sunghee-hwang — APPROVED** [review]

**Pull request merged**
